branches:
    only:
        - master

language: node_js
node_js:
    - lts/*
cache:
    directories:
        - node_modules

install:
    - npm install
script:
    - npm run build
    - echo source/ >> .gitignore
    - echo \!dist/ >> .gitignore
deploy:
    provider: pages
    on:
        branch: master
    skip_cleanup: true
    target_branch: release
    token: ${TOKEN}
